---
- name: Install couchdb
  hosts: targets
  become: true

  tasks:
    - name: ensure couchdb is at the latest version
      apt: name=couchdb state=latest

    - name: Bind Node Address to Public
      lineinfile:
        dest: /etc/couchdb/local.ini
        insertafter: '^\[httpd\]$'
        line: 'bind_address = 0.0.0.0'

    - name: start couchdb
      service:
          name: couchdb
          state: restarted

